config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users
    resources :users
    get 'pages/main'
    get '/contact', to: 'pages#contact'
    
    resources :subscriptions, only: [:create]

    resources :paintings do
      resources :images, only: [:create, :destroy]
    end
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    root "pages#main"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :painting
  mount_uploader :image, ImageUploader
end

app/models/painting.rb
class Painting < ApplicationRecord
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  validates :en_title, presence: true
  validates :es_title, presence: true
  validates :en_description, presence: true
  validates :es_description, presence: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  validates :email, uniqueness: true, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  validates :name_en, presence: true, length: { maximum: 255 }
  validates :name_es, length: { maximum: 255 }
  validates :admin, inclusion: { in: [true, false] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :switch_locale

  private

  def switch_locale(&action)
    locale = locale_from_url || locale_from_headers || I18n.default_locale
    response.set_header "Content-Language", locale
    I18n.with_locale locale, &action
  end

  def locale_from_url
    locale = params[:locale]

    return locale if I18n.available_locales.map(&:to_s).include?(locale)
  end

  def locale_from_headers
    header = request.env["HTTP_ACCEPT_LANGUAGE"]

    return if header.nil?

    locales = header.gsub(/\s+/, '').split(",").map do |language_tag|
      locale, quality = language_tag.split(/;q=/i)
      quality = quality ? quality.to_f : 1.0
      [locale, quality]
    end.reject do |(locale, quality)|
      locale == '*' || quality == 0
    end.sort_by do |(_, quality)|
      quality
    end.map(&:first)

    return if locales.empty?

    if I18n.enforce_available_locales
      locale = locales.reverse.find { |locale| I18n.available_locales.any? { |al| match?(al, locale) } }
      if locale
        I18n.available_locales.find { |al| match?(al, locale) }
      end
    else
      locales.last
    end
  end

  def match?(s1, s2)
    s1.to_s.casecmp(s2.to_s) == 0
  end

  def default_url_options
    { locale: I18n.locale}
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_painting
  before_action :set_image, only: [:destroy]
  
  def create
    @image = @painting.images.build(image_params)
    if @image.save
      redirect_to edit_painting_path(@painting), notice: 'Image was successfully added.'
    else
      render 'paintings/edit'
    end
  end

  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to edit_painting_path(@painting), notice: 'Image was successfully removed.' }
      format.js   # Это будет искать шаблон destroy.js.erb
    end
  end
  
  private
  
  def set_painting
    @painting = Painting.find(params[:painting_id])
  end
  
  def set_image
    @image = Image.find(params[:id])
  end
  
  def image_params
    params.require(:image).permit(:image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def main
    @paintings = Painting.order(created_at: :desc).limit(5)
    @user = current_user
  end

  def contact
    @user = current_user
  end
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy] 
  before_action :set_painting, only: %i[show edit update destroy]

  def index
    @paintings = Painting.all
    @user = current_user
  end

  def show
    @prev_painting = Painting.where("id < ?", @painting.id).order(id: :desc).first
    @next_painting = Painting.where("id > ?", @painting.id).order(id: :asc).first
    @user = current_user
  end

  def new
    @painting = Painting.new
  end

  def create
    @painting = Painting.new(painting_params)
    if @painting.save
      redirect_to edit_painting_path(@painting), notice: 'Painting was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @painting.update(painting_params)
      redirect_to @painting, notice: 'Painting was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @painting.destroy
    redirect_to root_path, notice: 'Painting was successfully destroyed.'
  end

  private

  def set_painting
    @painting = Painting.find(params[:id])
  end

  def painting_params
    params.require(:painting).permit(:en_title, :en_description, :es_title, :es_description, :creation_date, images_attributes: [:id, :image, :_destroy])
  end
end

app/controllers/subscriptions_controller.rb
# app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def create
    @subscription = Subscription.new(subscription_params)
    if @subscription.save
      redirect_to root_path, notice: 'You are subscribed!'
    else
      redirect_to root_path, alert: 'Invalid Email!'
    end
  end

  private
  def subscription_params
    params.require(:subscription).permit(:email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
  end
  
  def new
    @user = User.new
  end
  
  def edit
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end
  
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end
  
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def user_params
    params.require(:user).permit(:name_en, :name_es, :info_en, :info_es, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Narciso Perez Fine Art</title>
  <!-- mobile responsive meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  
  <!-- theme meta -->
  <meta name="theme-name" content="galaxy" />

  <!-- ** Plugins Needed for the Project ** -->
  <!-- Bootstrap, Main Stylesheet and other necessary stylesheets are linked here -->

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/glightbox/3.2.0/js/glightbox.min.js" integrity="sha512-S/H9RQ6govCzeA7F9D0m8NGfsGf0/HjJEiLEfWGaMCjFzavo+DkRbYtZLSO+X6cZsIKQ6JvV/7Y9YMaYnSGnAA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/glightbox/3.2.0/js/glightbox.js" integrity="sha512-B15xrHLAFUGC5w4jO8iQtCLLaliORCeLUCewc3Pjrtzw6y2ZXECO6bHalENItF5p/yPpz02fGL/luT/Bs17WnA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/glightbox/3.2.0/css/glightbox.css" integrity="sha512-iQ3H4A+iyBTP8M4ypX5PrTt2S+G1zmRjf0k0uOASKlFHysV8TL9ZoQyVwPss0D12IBTMoDEHA8+bg8a1viS9Mg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/glightbox/3.2.0/css/glightbox.min.css" integrity="sha512-T+KoG3fbDoSnlgEXFQqwcTC9AdkFIxhBlmoaFqYaIjq2ShhNwNao9AKaLUPMfwiBPL0ScxAtc+UYbHAgvd+sjQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

  <!--Favicon-->
  <%= favicon_link_tag asset_path('favicon.png') %>
</head>
<body>
  <!-- Assuming you have a partial header -->
    <section class="d-flex">

        <%= render partial: 'partials/sidenav', locals: {home: 'active', about: '', contact: '', pages: '', home2: '', category: '', postDetails: '', pnp: ''} %>

        <div class="main-content">
            <%= render partial: 'partials/mobile-nav' %>
            <div class="container pt-4 mt-5 d-flex justify-content-center">
                <div class="d-flex justify-content-between w-100 flex-wrap">
                    <div class="col-lg-7 col-12">
                        <% flash.each do |message_type, message| %>
                            <div class="alert alert-<%= message_type %>">
                                <%= message %>
                            </div>
                        <% end %>

                        <div class="col-12">
                            <%= yield %>
                        </div>
                    </div>
                    <div class="col-lg-4 col-12 px-0">
                        <%= render "partials/author" %>
                    </div>
                </div>
            </div>
        </div>

    </section>
    <%= render partial: 'partials/footer-block' %>
</body>
</html>

app/views/pages/contact.html.erb
<div class="container contact-container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title"><%= t "contact.contact_me_via" %></h5>
                    
                    <div class="mt-3">
                        <i class="bi bi-whatsapp "></i> <%= t "contact.whatsapp" %> <%= link_to "+18098628384", "https://wa.me/+18296294794", target: "_blank", class:"cont-link" %>
                    </div>
                    
                    <div class="mt-3">
                        <i class="bi bi-facebook"></i> <%= t "contact.facebook" %> <%= link_to "Narciso Perez", "https://www.facebook.com/narciso.perez.3950178", target: "_blank", class:"cont-link" %>
                    </div>
                    
                    <div class="mt-3">
                        <i class="bi bi-instagram"></i> <%= t "contact.instagram" %> <%= link_to "NarcisoP", "https://www.instagram.com", target: "_blank", class:"cont-link" %>
                    </div>
                    
                    <div class="mt-3">
                        <i class="bi bi-envelope-fill"></i> <%= t "contact.email" %> <%= mail_to "narciso@perez.do", class:"cont-link" %>
                    </div>
                    
                    <div class="mt-3">
                        <i class="bi bi-telephone-fill"></i> <%= t "contact.phone" %> <%= link_to "+18098628384", "tel:+18098628384", class:"cont-link" %>
                    </div>

                    <div class="mt-3">
                        <i class="bi bi-geo-alt-fill"></i> <%= t "contact.address" %> <%= link_to 'Puerto Plata, DR', 'https://www.google.com/maps/search/?api=1&query=Purto+Plata', target: '_blank', class:"cont-link" %>
                    </div>
              </div>
            </div>
        </div>
    </div>
</div>

app/views/pages/main.html.erb
<h2><%= t "paintings.latest_artworks_title" %></h2>
<h3><%= t "paintings.explore_creations" %></h3>
<br>
<%= render @paintings %>

app/views/paintings/_form.html.erb
<%= form_for @painting, html: { class: 'form-group my-2 mb-4', multipart: true } do |f| %>
  <div class="mb-3">
    <%= f.label :en_title, t('paintings.form.english_title'), class: 'form-label' %>
    <%= f.text_field :en_title, class: 'form-control', placeholder: t('paintings.form.enter_english_title') %>
  </div>

  <div class="mb-3">
    <%= f.label :en_description, t('paintings.form.english_description'), class: 'form-label' %>
    <%= f.text_area :en_description, class: 'form-control', placeholder: t('paintings.form.enter_english_description') %>
  </div>

  <div class="mb-3">
    <%= f.label :es_title, t('paintings.form.spanish_title'), class: 'form-label' %>
    <%= f.text_field :es_title, class: 'form-control', placeholder: t('paintings.form.enter_spanish_title') %>
  </div>
  
  <div class="mb-3">
    <%= f.label :es_description, t('paintings.form.spanish_description'), class: 'form-label' %>
    <%= f.text_area :es_description, class: 'form-control', placeholder: t('paintings.form.enter_spanish_description') %>
  </div>

  <div class="mb-3">
    <%= f.label :creation_date, t('paintings.form.creation_date'), class: 'form-label' %>
    <%= f.date_field :creation_date, class: 'form-control' %>
  </div>
  
  <%= f.submit t('save'), class: 'btn btn-primary me-2' %>
  <%= link_to t('back'), :back, class: 'btn btn-secondary' %>
<% end %>

app/views/paintings/_painting.html.erb
<div class="card post-item bg-transparent border-0 mb-5">
    <div class="painting-section">
        <%= link_to painting_path(painting) do %>
            <%= image_tag painting.images.first.image.url, alt: 'Narciso Perez Fine Art', class: 'painting-image rounded-0' if painting.images.any? %>
        <% end %>
    </div>
    <div class="card-body px-0">
        <h2 class="card-title">
            <% title_field = %w[en es].include?(I18n.locale.to_s) ? "#{I18n.locale}_title".to_sym : :en_title %>
            <%= link_to painting[title_field], painting_path(painting), class: 'text-white opacity-75-onHover' %>
        </h2>
        <ul class="post-meta mt-3">
            <li class="d-inline-block me-4">
                <span class="bi-card-list text-primary fs-6"></span>
                <span class="mx-2 text-white fs-6"><%= t('paintings.post_item.fine_art') %></span>
            </li>
            <% if painting.creation_date.present? %>
                <li class="d-inline-block">
                    <span class="bi-clock text-primary fs-6"></span>
                    <span class="mx-2 text-white fs-6"><%= l painting.creation_date, format: :long %></span>
                </li>
            <% end %>
        </ul>
        <p class="card-text my-4">
          <% description_field = %w[en es].include?(I18n.locale.to_s) ? "#{I18n.locale}_description".to_sym : :en_description %>
          <%= painting[description_field].try(:truncate, 30) || t('default_description') %>
        </p>
        <%= link_to t('paintings.post_item.see_details'), painting_path(painting), class: 'btn btn-primary fs-6' %>
    </div>
</div>
<hr>

app/views/paintings/edit.html.erb
<div class="flex">
  <span class="d-flex">
    <h2 class="me-2"><%= t("paintings.edit.edit_painting") %></h2>
    <%= link_to t("paintings.edit.this_painting_page"), painting_path(@painting), class: "btn btn-outline-warning border border-light px-2 rounded " %>
  </span>
  
  <div class="container image-container">
    <div class="card bg-dark text-white">
      <div class="card-title">
        <h3 class="ms-3 mt-4"><%= t("paintings.edit.add_new_image") %></h3>
      </div>
      <div class="card-body">
        <p>First go to gray button to attach image from your phone bro</p>
        <%= form_for [ @painting, Image.new ], url: painting_images_path(@painting), html: { multipart: true } do |f| %>
          <div class="form-group my-2">
            <%= f.label :image, t("paintings.edit.upload_image") %><br>
            <%= f.file_field :image %>
          </div>
          <%= f.submit t("paintings.edit.upload_image"), class: "btn btn-success fs-6" %>
        <% end %>

        <% if @painting.images.count > 0 %>
          <h3 class="my-2 mt-4"><%= t("paintings.edit.images") %></h3>
          <div class="d-flex justify-content-center">
            <div class="image-list">
              <% @painting.images.each do |image| %>
                <div class="image-item mb-2">
                  <div class="image-thumb">
                    <%= image_tag image.image.url(:thumb), class:"thumb-size" if image.image.present? %>
                  </div>
                  <div class="image-info">
                    <p><%= image.image.identifier %></p> <!-- File Name -->
                  </div>
                  <div class="image-action">
                    <%= button_to t("paintings.edit.delete"), painting_image_path(@painting, image), method: :delete, data: { turbo_confirm: t("paintings.edit.delete_image_confirmation") }, class: "btn btn-danger fs-6" %>
                  </div>
                </div>
                <hr>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <%= render "form" %>
</div>

app/views/paintings/index.html.erb
<%= render @paintings %>

app/views/paintings/new.html.erb
<div class="flex">
  <h2><%= t('paintings.new.new_painting') %></h2>
  <p class="my-2"><%= t('paintings.new.first_you_name') %></p>
  <%= render 'form' %>
  <p class="mb-2"><%= t('paintings.new.save_and_edit') %></p>
</div>

app/views/paintings/show.html.erb
<div class="card post-item bg-transparent border-0">
  <div class="card-body px-0">
    <h2 class="card-title text-white">
      <% title_field = %w[en es].include?(I18n.locale.to_s) ? "#{I18n.locale}_title".to_sym : :en_title %>
      <%= @painting[title_field] || @painting[:en_title] %>
    </h2>
  </div>
</div>

<% if @painting.images.any? %>
  <hr class="my-4">
  <section class="gallery-section position-relative mb-4">
    <div id="carouselEventControls" class="carousel slide carousel-fade" data-bs-ride="carousel">
      <div class="carousel-inner">
        <% @painting.images.each_with_index do |image, index| %>
          <div class="carousel-item <%= 'active' if index.zero? %> text-center">
            <%= link_to image.image.url, class: "gallery-lightbox", data: { glightbox: '', turbo: false } do %>
              <%= image_tag image.image.url, class: "d-block w-100", alt: "", style: "object-fit: cover; max-height: 600px;" %>
            <% end %>
          </div>
        <% end %>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselEventControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselEventControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </section>
<% end %>

<!-- Добавленный блок навигации -->
<div class="d-flex justify-content-center mt-3 mb-3">
  <% if @prev_painting %>
    <%= link_to painting_path(@prev_painting), class: 'btn btn-outline-secondary border rounded-4 d-flex align-items-center', data: { turbo: false } do %>
      <i class="bi bi-arrow-left mx-0"></i><span class="d-none d-md-block mx-2"><%= t('paintings.show.previous_painting') %></span>
    <% end %>
  <% end %>

  <%= link_to paintings_path, class: 'btn btn-outline-secondary border rounded-4 d-flex align-items-center mx-4' do %>
    <i class="bi bi-grid-3x3-gap mx-0"></i><span class="d-none d-md-block mx-2"><%= t('paintings.show.all_paintings') %></span>
  <% end %>

  <% if @next_painting %>
    <%= link_to painting_path(@next_painting), class: 'btn btn-outline-secondary border rounded-4 d-flex align-items-center', data: { turbo: false } do %>
      <span class="d-none d-md-block mx-2"><%= t('paintings.show.next_painting') %> </span><i class="bi bi-arrow-right mx-0"></i>
    <% end %>
  <% end %>
</div>

<div class="card post-item bg-transparent border-0 mb-5">
  <div class="card-body px-0">
    <p class="card-text">
      <% description_field = %w[en es].include?(I18n.locale.to_s) ? "#{I18n.locale}_description".to_sym : :en_description %>
      <%= @painting[description_field] || @painting[:en_description] %>
    </p>
    <ul class="post-meta mt-3">
      <li class="d-inline-block">
        <span class="bi-card-list text-primary"></span>
        <span class="mx-2 text-white"><%= t('paintings.show.fine_art') %></span>
      </li>
      <% if @painting.creation_date.present? %>
        <li class="d-inline-block mx-4">
          <span class="bi-clock text-primary"></span>
          <span class="mx-2 text-white"><%= l @painting.creation_date, format: :long %></span>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<div class="text-start d-flex">
  <% if @user.present? && @user.admin? %>
    <div class="mb-2 d-flex">
      <%= link_to t('paintings.show.edit'), edit_painting_path, class: 'btn btn-success me-2' %>
      <%= button_to t('paintings.show.delete'), painting_path(@painting), method: :delete, class: 'btn btn-danger', data: { turbo_confirm: t('paintings.show.confirm_delete') } %>
    </div>
  <% end %>
</div>

app/views/partials/_author.html.erb
<div class="widget text-center mt-5 mt-md-0">
    <%= image_tag 'author.jpg', alt: '', class: 'author-thumb-sm rounded-circle d-block mx-auto' %>                        
    <h2 class="widget-title text-white d-inline-block mt-4"><%= t('author_widget.title') %></h2>
    <p class="mt-4">
        <%= t('author_widget.description') %>
    </p>
    <ul class="list-inline mt-3">
        <li class="list-inline-item">
            <a href="https://wa.me/+18296294794" target="_blank" class="text-white text-primary-onHover p-2">
                <span class="bi-whatsapp"></span>
            </a>
        </li>        <li class="list-inline-item">
            <a href="https://www.facebook.com/narciso.perez.3950178" target="_blank" class="text-white text-primary-onHover p-2">
                <span class="bi-facebook"></span>
            </a>
        </li>
        <li class="list-inline-item">
            <a href="https://www.instagram.com" target="_blank" class="text-white text-primary-onHover p-2">
                <span class="bi-instagram"></span>
            </a>
        </li>
        <li class="list-inline-item">
            <a href="mailto:narciso@perez.do" class="text-white text-primary-onHover p-2">
                <span class="bi-envelope-fill"></span>
            </a>
        </li>
        <li class="list-inline-item">
            <a href="tel:+18098628384" class="text-white text-primary-onHover p-2">
                <span class="bi-telephone-fill"></span>
            </a>
        </li>
    </ul>
</div>

<div class="widget bg-dark p-4 text-center">
    <h2 class="widget-title text-white d-inline-block mt-4"><%= t('subscribe_widget.title') %></h2>
    <p class="mt-4"><%= t('subscribe_widget.description') %></p>
    <%= form_with(model: Subscription.new, local: false, data: { controller: "subscription" }) do |form| %>
        <%= form.email_field :email, placeholder: t('subscribe_widget.placeholder'), class:"form-control bg-black text-white", data: { action: "input->clear_field#clear" } %><br>
        <%= form.submit t('subscribe_widget.button'), class: 'btn btn-primary fs-6 my-2' %>
    <% end %>
</div>

app/views/partials/_mobile-nav.html.erb
<!-- start of mobile-nav -->
<header class="mobile-nav pt-4">
    <div class="container">
        <div class="d-flex align-items-center">
            <div class="col-6">
                <%= link_to root_path do %>
                    <%= image_tag "logo.png" %>
                <% end %>
            </div>
            <div class="col-6 d-flex justify-content-end align-items-center">
                <button class="nav-toggle bg-transparent border text-white d-flex justify-content-center align-items-center">
                    <span class="bi bi-list mx-0"></span>
                </button>
            </div>
        </div>
    </div>
</header>
<div class="nav-toggle-overlay"></div>
<!-- end of mobile-nav -->

app/views/partials/_sidenav.html.erb
<aside><div class="sidenav position-sticky d-flex flex-column justify-content-between">
    <%= link_to root_path, class:"navbar-brand logo" do %>
        <%= image_tag "logo.png" %>
    <% end %>

    <div class="navbar navbar-dark my-4 p-0 font-primary">
        <ul class="navbar-nav w-100">
            <li class="nav-item">
                <%= link_to t('sidenav.home'), root_path, class:"nav-link text-white px-0 pt-0" %>
            </li>
            <li class="nav-item">
                <%= link_to t('sidenav.art_gallery'), paintings_path, class:"nav-link text-white px-0" %>
            </li>
            <li class="nav-item">
                <%= link_to t('sidenav.contact'), contact_path, class:"nav-link text-white px-0" %>
            </li>
            <% if @user.present? && @user.admin? %>
                <li class="nav-item">
                    <%= link_to t('sidenav.new_painting'), new_painting_path, class:"nav-link text-white px-0" %>
                </li>
            <% end %>
            <%= select_tag 'locale', 
                options_for_select(I18n.available_locales.sort.map { |locale| [I18n.t("locales.#{locale}"), url_for(locale: locale)] }, selected: url_for(locale: I18n.locale)), 
                class: 'custom-select bg-transparent rounded-0 text-white shadow-none mt-3 w-auto', 
                onchange: 'window.location = this.value' 
            %>
        </ul>
    </div>

    <ul class="list-inline nml-2">
        <li class="list-inline-item">
            <a href="#!" class="text-white text-red-onHover pr-2">
                <span class="fab fa-twitter"></span>
            </a>
        </li>
        <li class="list-inline-item">
            <a href="#!" class="text-white text-red-onHover p-2">
                <span class="fab fa-facebook-f"></span>
            </a>
        </li>
        <li class="list-inline-item">
            <a href="#!" class="text-white text-red-onHover p-2">
                <span class="fab fa-instagram"></span>
            </a>
        </li>
        <li class="list-inline-item">
            <a href="#!" class="text-white text-red-onHover p-2">
                <span class="fab fa-linkedin-in"></span>
            </a>
        </li>
    </ul>
    <!-- end of social-links -->
</div></aside>
<!-- end of sidenav -->

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>
<div class="main-content">
  <div class="container pt-4 mt-5">
    <div class="row justify-content-center">
      <div class="col-lg-7">
        <h1 class="text-white">Edit User</h1>
        <%= render 'form', user: @user %>
        <%= link_to 'Back', users_path, class: 'btn btn-secondary mt-3' %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main-content">
    <div class="container pt-4 mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-7">
                <div class="card post-item bg-transparent border-0">
                    <div class="card-body px-0">
                        <h1 class="text-white">User: <%= @user.name %></h1>
                        <p class="text-white mt-4">
                            <strong>Email:</strong> <%= @user.email %>
                        </p>
                        <p class="text-white mt-4">
                            <strong>Info:</strong> <%= @user.info %>
                        </p>

                        <div class="actions mt-3">
                            <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-primary' %>
                            <%= link_to 'Back', users_path, class: 'btn btn-secondary' %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>